/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IncidentsIdRouteImport } from './routes/incidents.$id'
import { Route as IncidentsIdArtifactsHashRouteImport } from './routes/incidents.$id_.artifacts.$hash'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIdRoute = IncidentsIdRouteImport.update({
  id: '/incidents/$id',
  path: '/incidents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIdArtifactsHashRoute =
  IncidentsIdArtifactsHashRouteImport.update({
    id: '/incidents/$id_/artifacts/$hash',
    path: '/incidents/$id/artifacts/$hash',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/incidents/$id': typeof IncidentsIdRoute
  '/incidents/$id/artifacts/$hash': typeof IncidentsIdArtifactsHashRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/incidents/$id': typeof IncidentsIdRoute
  '/incidents/$id/artifacts/$hash': typeof IncidentsIdArtifactsHashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/incidents/$id': typeof IncidentsIdRoute
  '/incidents/$id_/artifacts/$hash': typeof IncidentsIdArtifactsHashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/incidents/$id' | '/incidents/$id/artifacts/$hash'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/incidents/$id' | '/incidents/$id/artifacts/$hash'
  id: '__root__' | '/' | '/incidents/$id' | '/incidents/$id_/artifacts/$hash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IncidentsIdRoute: typeof IncidentsIdRoute
  IncidentsIdArtifactsHashRoute: typeof IncidentsIdArtifactsHashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/$id': {
      id: '/incidents/$id'
      path: '/incidents/$id'
      fullPath: '/incidents/$id'
      preLoaderRoute: typeof IncidentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/$id_/artifacts/$hash': {
      id: '/incidents/$id_/artifacts/$hash'
      path: '/incidents/$id/artifacts/$hash'
      fullPath: '/incidents/$id/artifacts/$hash'
      preLoaderRoute: typeof IncidentsIdArtifactsHashRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IncidentsIdRoute: IncidentsIdRoute,
  IncidentsIdArtifactsHashRoute: IncidentsIdArtifactsHashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
